# Generated by Django 6.1 on 2026-08-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_subject_alter_admin_email_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='approved', max_length=20),
        ),
    ]
