# Generated by Django 6.1 on 2026-08-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_student_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='pending_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='pending_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
