# Generated by Django 6.1 on 2026-08-27 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_student_pending_email_student_pending_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
    ]
